name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

  Continuous-Deployment:
    name: Continuous Deployment
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Check Node Version
        run: npm -v

      - name: Install Paperspace Cli
        run: npm install -g paperspace-node

      - name: Test Paperspace Cli
        run: paperspace -version

      - name: Start a Gpu Instance
        run: paperspace machines start --apiKey ${{ secrets.API_KEY }} --machineId ${{ secrets.MACHINE_ID }}

      - name: Wait For Instance state to be ready
        run: paperspace machines waitfor --apiKey ${{ secrets.API_KEY }} --machineId ${{ secrets.MACHINE_ID }} --state "ready"

  Continuous-Training:
    name: Continuous Training
    needs: Continuous-Deployment
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Training Pipeline
        run: |
          cd actions-runner && cd _work
          cd SearchEngine-ModelTrainingEndpoint
          cd SearchEngine-ModelTrainingEndpoint
          conda create -p ./env python=3.9 -y
          conda activate ./env
          pip3 install -r requirements.txt
          python src/pipeline/pipeline.py 
          conda deactivate ./env 
          rm -rf env

      - name: Training Completed
        run: echo "Training Completed"

  Clean-Workbench:
    name: Clean Workbench
    needs: Continuous-Training
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Paperspace Cli
        run: npm install -g paperspace-node

      - name: Stop Running Instance
        run: paperspace machines stop --apiKey ${{ secrets.API_KEY }} --machineId ${{ secrets.MACHINE_ID }}

      - name: Wait For Instance state to be Stopped
        run: paperspace machines waitfor --apiKey ${{ secrets.API_KEY }} --machineId ${{ secrets.MACHINE_ID }} --state "off"

      - name: Job Completed
        run: echo "Completed Training Stage"
