name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"


  Continuous-Deployment:
    name: Continuous Deployment
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Check Node Version
        run: npm -v

      - name: Install Paperspace Cli
        run: npm install -g paperspace-node

      - name: Test Paperspace Cli
        run: paperspace -version

      - name: Start a Gpu Instance
        run: paperspace machines start --apiKey ${{ secrets.API_KEY }} --machineId ${{ secrets.MACHINE_ID }}

  Continuous-Training:
    name: Continuous Training
    needs: Continuous-Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Connection Pass
        run: sudo apt-get install sshpass

      - name: Create SSh Connection
        run: sshpass -p ${{ secrets.SSH_PASSWORD }} ssh paperspace@64.62.141.2

      - name: Who AM I
        run: whoami

      - name: ShutDown Remote Machine
        run: sudo shutdown now

